### ISSUE TITLE
Fix vulnerable packages

### ISSUE THREAD

**Issue by subeshb1** [subeshb1/infinity-react-carousel#10]
There are a lot of vulnerable packages in this project. We need to patch them

**Comment by subeshb1** [comment]
@oznakn sure go ahead

**Comment by oznakn** [comment]
Hi, I created #14.

The vulnerable packages are _jest_ and _@storybook/addon-info_. The _jest_ package is updated but the vulnerability in _@storybook/addon-info_ has not been fixed by its authors.

**Comment by subeshb1** [comment]
Thanks! we can address i`@storybook/addon-info`
